[build]
  publish = "build"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Enable SPA prerendering for better SEO
[[prerendering]]
  crawl = true
  include = ["/", "/movies", "/tvshows", "/movie/*", "/tvshow/*"]

# Redirect movie routes to Next.js (if Next.js is deployed separately)
# For now, redirect all routes to index.html (React app)
[[redirects]]
  from = "/movie/:id"
  to = "https://streammoviestream.netlify.app/movie/:id"
  status = 200
  force = true

# Handle client-side routing - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control headers
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
