[build]
  command = "npm run build"
  publish = ".next"

# Plugin for Next.js SSR support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Environment variables will be set in Netlify dashboard
